name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: Deployment
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: deploy
    - name: Build mr-worldwide JAR
      run: >-
        clojure -T:build build '{:project mr-worldwide}'
      env:
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
    - name: Deploy mr-worldwide to Clojars
      run: >-
        clojure -T:build deploy '{:project mr-worldwide}'
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_TOKEN_CORE }}
    - name: Build mr-worldwide.build JAR
      run: >-
        clojure -T:build build '{:project mr-worldwide.build}'
      env:
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
    - name: Deploy mr-worldwide.build to Clojars
      run: >-
        clojure -T:build deploy '{:project mr-worldwide.build}'
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_TOKEN_BUILD }}
