name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  kondo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java & Clojure
        uses: ./.github/actions/setup-clojure
        with:
          cache-key: kondo
      - name: Run Kondo
        run: >-
          ./bin/kondo.sh

  tests-mr-worldwide:
    name: Run tests (mr-worldwide)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: tests
    - run: clojure -X:test/mr-worldwide
      name: Run tests
      env:
        CI: TRUE

  tests-mr-worldwide-build:
    name: Run tests (mr-worldwide.build)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: tests-build
    - run: clojure -X:test/mr-worldwide.build
      name: Run tests
      env:
        CI: TRUE

  tests-mr-worldwide-cljs:
    name: Run CLJS tests (mr-worldwide)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: tests-cljs
    - uses: actions/setup-node@v4
    - name: Install packages
      run: >-
        npm install
    - name: Build CLJS bundle
      run: >-
        ./node_modules/.bin/shadow-cljs compile test
    - name: Run tests
      run: >-
        node target/node-tests.js

  whitespace-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: whitespace-linter
    - run: clojure -T:whitespace-linter
      name: Run whitespace linter

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: check
    - run: clojure -M:check
      name: Check namespaces

  # codecov:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup Java & Clojure
  #     uses: ./.github/actions/setup-clojure
  #     with:
  #       cache-key: codecov
  #   - run: clojure -X:dev:test-h2:cloverage
  #     name: Run tests with Cloverage
  #   - name: Upload results to codecov.io
  #     uses: codecov/codecov-action@v3
  #     with:
  #       files: ./target/coverage/codecov.json

  # codespell:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: codespell-project/actions-codespell@master
